project_id = "alqibsaatuqpbmgmscll"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.openai-chat]
verify_jwt = false

[functions.scrape-ads]
verify_jwt = true

[functions.generate-articles]
verify_jwt = true

[functions.scrape-ads-auto]
verify_jwt = false

[functions.scrape-ads-enhanced]
verify_jwt = false