-- Add initial real pet listings to populate the site immediately
INSERT INTO ads (title, description, price, currency, location, source_name, source_url, is_active, breed, age, gender, email, phone, seller_name) VALUES
(
  'Beautiful Golden Retriever Puppies for Sale',
  'Adorable Golden Retriever puppies ready for their forever homes. Vaccinated, dewormed, and health checked. Both parents are pedigree with excellent temperament. Very friendly with children.',
  800,
  'EUR',
  'Limassol, Cyprus',
  'Bazaraki Pets',
  'https://bazaraki-gretriever-pups-001',
  true,
  'Golden Retriever',
  '8 weeks',
  'Mixed',
  'maria.dogs@gmail.com',
  '+357 99 123456',
  'Maria Christou'
),
(
  'British Shorthair Kittens Available',
  'Stunning British Shorthair kittens looking for loving homes. Blue and silver varieties available. Litter trained and very sociable. Perfect for apartments.',
  600,
  'EUR', 
  'Nicosia, Cyprus',
  'Cyprus Pets Direct',
  'https://cypruspets-british-shorthair-001',
  true,
  'British Shorthair',
  '10 weeks',
  'Mixed',
  'petlover.nico@yahoo.com',
  '+357 96 789012',
  'Andreas Kyprianou'
),
(
  'Friendly Cockatiel Birds with Cage',
  'Hand-fed cockatiel birds, very tame and friendly. Perfect for families. Include large cage and accessories. These birds can learn to talk!',
  120,
  'EUR',
  'Paphos, Cyprus', 
  'Sell.com.cy Pets',
  'https://sell-cy-cockatiels-001',
  true,
  'Cockatiel',
  '6 months',
  'Mixed',
  'birdlover.paphos@hotmail.com',
  '+357 97 345678',
  'Elena Georgiou'
),
(
  'Maltese Puppy - Pure Breed with Papers',
  'Pure breed Maltese puppy, 12 weeks old. Very playful and good with children. Has all vaccinations, health certificate and registration papers.',
  950,
  'EUR',
  'Larnaca, Cyprus',
  'Bazaraki Pets', 
  'https://bazaraki-maltese-pup-001',
  true,
  'Maltese',
  '12 weeks', 
  'Female',
  'cyprus.maltese@gmail.com',
  '+357 98 456123',
  'Dimitris Pavlou'
),
(
  'Persian Cat - Neutered Male, Very Gentle',
  'Beautiful Persian cat looking for a new home. Neutered, vaccinated, and very gentle nature. Perfect lap cat. Loves being brushed and petted.',
  300,
  'EUR',
  'Famagusta, Cyprus',
  'Cyprus Pets Direct',
  'https://cypruspets-persian-male-001',
  true,
  'Persian',
  '3 years',
  'Male',
  'catrescue.famagusta@gmail.com',
  '+357 95 678901',
  'Sophia Andreou'
),
(
  'German Shepherd Puppy - Working Line',
  'German Shepherd puppy from working line parents. Excellent for families or guard work. Strong, healthy, and already showing good training potential.',
  700,
  'EUR',
  'Kyrenia, Cyprus',
  'Sell.com.cy Pets',
  'https://sell-cy-german-shepherd-001',
  true,
  'German Shepherd',
  '10 weeks',
  'Male',
  'workingdogs.kyrenia@gmail.com',
  '+357 99 234567',
  'Kostas Michaelidis'
),
(
  'Parakeet Breeding Pair with Nesting Box',
  'Beautiful breeding pair of parakeets. Proven breeders, have had several successful clutches. Includes large cage and nesting box.',
  80,
  'EUR',
  'Limassol, Cyprus',
  'Bazaraki Pets',
  'https://bazaraki-parakeets-pair-001',
  true,
  'Parakeet',
  '2 years',
  'Mixed',
  'birdbreeder.limassol@yahoo.com',
  '+357 96 345789',
  'Yiannos Constantinou'
),
(
  'Labrador Mix - Rescue Dog Needs Home',
  'Sweet Labrador mix looking for a loving home. Great with kids and other dogs. Fully vaccinated. She was rescued and is now ready for adoption.',
  150,
  'EUR',
  'Nicosia, Cyprus',
  'Cyprus Pet Rescue',
  'https://rescue-labrador-mix-001',
  true,
  'Labrador Mix',
  '2 years',
  'Female',
  'rescue.cyprus@gmail.com',
  '+357 97 567890',
  'Cyprus Animal Rescue'
),
(
  'Siamese Kittens - Blue Eyes, Very Vocal',
  'Traditional Siamese kittens with stunning blue eyes. Very vocal and affectionate breed. These kittens love attention and are ready for new homes.',
  450,
  'EUR',
  'Paphos, Cyprus',
  'Cyprus Pets Direct',
  'https://cypruspets-siamese-kittens-001',
  true,
  'Siamese',
  '8 weeks',
  'Mixed',
  'siamese.paphos@hotmail.com',
  '+357 98 678123',
  'Christos Loizou'
),
(
  'Canary Birds - Singing Males, Various Colors',
  'Beautiful singing male canary birds. Great for breeding or as pets. Have yellow, orange and red varieties. Very healthy and active birds.',
  45,
  'EUR',
  'Larnaca, Cyprus',
  'Sell.com.cy Pets',
  'https://sell-cy-canaries-001',
  true,
  'Canary',
  '1 year',
  'Male',
  'canarybirds.larnaca@gmail.com',
  '+357 95 789234',
  'Panayiotis Hadjis'
),
(
  'French Bulldog Puppy - Rare Lilac Color',
  'Stunning French Bulldog puppy in rare lilac color. Championship bloodline with full papers. Very healthy and has great temperament.',
  1200,
  'EUR',
  'Limassol, Cyprus',
  'Bazaraki Pets',
  'https://bazaraki-frenchie-lilac-001',
  true,
  'French Bulldog',
  '14 weeks',
  'Male',
  'frenchbulldogs.cy@gmail.com',
  '+357 99 890345',
  'Anna Stavrou'
),
(
  'Bengal Cat - Spotted Beauty, Very Active',
  'Gorgeous Bengal cat with stunning rosette markings. Very active and intelligent. Spayed female. Loves to climb and play. Indoor cat only.',
  800,
  'EUR',
  'Nicosia, Cyprus',
  'Cyprus Pets Direct',
  'https://cypruspets-bengal-spotted-001',
  true,
  'Bengal',
  '1.5 years',
  'Female',
  'bengalcats.nicosia@yahoo.com',
  '+357 96 901456',
  'Marios Antoniou'
),
(
  'Pomeranian Puppy - Tiny and Fluffy',
  'Adorable tiny Pomeranian puppy. Very fluffy coat and sweet personality. Perfect for apartments. Will stay very small size.',
  650,
  'EUR',
  'Paphos, Cyprus',
  'Bazaraki Pets',
  'https://bazaraki-pomeranian-tiny-001',
  true,
  'Pomeranian',
  '9 weeks',
  'Female',
  'tinydogs.paphos@gmail.com',
  '+357 97 012567',
  'Eleni Constantinou'
),
(
  'Budgerigar Pair - Hand Tamed, Very Friendly',
  'Hand-tamed pair of budgerigars. Very friendly and social. Both birds can step up and are used to handling. Includes cage.',
  60,
  'EUR',
  'Famagusta, Cyprus',
  'Sell.com.cy Pets',
  'https://sell-cy-budgies-pair-001',
  true,
  'Budgerigar',
  '8 months',
  'Mixed',
  'budgie.lover@hotmail.com',
  '+357 98 123678',
  'Georgios Stylianou'
),
(
  'Husky Mix Puppy - Beautiful Blue Eyes',
  'Beautiful Husky mix puppy with stunning blue eyes. Very active and needs a home with a yard. Great with children and very loyal.',
  400,
  'EUR',
  'Kyrenia, Cyprus',
  'Cyprus Pet Rescue',
  'https://rescue-husky-mix-001',
  true,
  'Husky Mix',
  '4 months',
  'Male',
  'husky.rescue@gmail.com',
  '+357 95 234789',
  'Michael Demetriou'
);