-- PHASE 3: ADD MORE AMAZON PRODUCTS
-- Insert additional high-quality Amazon products with Cyprus affiliate ID
INSERT INTO affiliate_products (
  title, 
  description, 
  short_description,
  external_product_id, 
  network_id, 
  price, 
  original_price,
  currency,
  affiliate_link, 
  image_url, 
  category, 
  subcategory,
  brand,
  rating,
  review_count,
  availability_status,
  is_active,
  is_featured,
  seo_title,
  seo_description,
  tags
) VALUES 
  -- Premium Dog Products
  (
    'Blue Buffalo Life Protection Formula Adult Dog Food, Chicken and Brown Rice',
    'Blue Buffalo Life Protection Formula Adult Dog Food is formulated to meet the nutritional levels established by the AAFCO Dog Food Nutrient Profiles for maintenance of adult dogs. Made with real chicken as the first ingredient, this premium dog food contains no chicken by-product meals, corn, wheat, or soy.',
    'Premium adult dog food with real chicken, ideal for Cyprus pet owners',
    'B00C5PRFW2',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    45.99,
    52.99,
    'EUR',
    'https://amzn.to/3Cyprus1',
    'https://m.media-amazon.com/images/I/81j+3Hb7AFL.jpg',
    'Food & Treats',
    'Dry Dog Food',
    'Blue Buffalo',
    4.5,
    15623,
    'in_stock',
    true,
    true,
    'Blue Buffalo Dog Food Cyprus - Premium Adult Chicken & Rice',
    'Buy Blue Buffalo Life Protection Formula Adult Dog Food in Cyprus. Premium nutrition with real chicken for your dog''s health.',
    ARRAY['dog food', 'premium nutrition', 'cyprus pets', 'chicken recipe', 'adult dogs']
  ),
  (
    'PetSafe Healthy Pet Simply Feed Automatic Dog and Cat Feeder',
    'The PetSafe Healthy Pet Simply Feed Automatic Feeder can dispense 1/8 cup to 4 cups of dry or semi-moist pet food. The built-in timer allows you to schedule up to 12 meals per day. Perfect for busy pet owners in Cyprus who want to maintain consistent feeding schedules.',
    'Automatic pet feeder for scheduled meals',
    'B00VIXRB6O',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    89.95,
    99.95,
    'EUR',
    'https://amzn.to/3Cyprus2',
    'https://m.media-amazon.com/images/I/71ZNQX6bq8L.jpg',
    'Feeding & Watering',
    'Automatic Feeders',
    'PetSafe',
    4.3,
    8945,
    'in_stock',
    true,
    true,
    'PetSafe Automatic Pet Feeder Cyprus - Schedule 12 Meals Daily',
    'Buy PetSafe automatic pet feeder in Cyprus. Perfect for busy pet owners - schedule up to 12 meals per day.',
    ARRAY['automatic feeder', 'pet care', 'cyprus pets', 'scheduled feeding', 'convenience']
  ),
  -- Premium Cat Products
  (
    'Hill''s Science Diet Adult Indoor Cat Food, Chicken Recipe',
    'Hill''s Science Diet Adult Indoor Cat Food provides precisely balanced nutrition for indoor cats. Made with natural ingredients and formulated by veterinarians and pet nutritionists. Supports healthy digestion and helps control hairballs.',
    'Veterinarian-recommended indoor cat food',
    'B00063KV9Q',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    38.99,
    42.99,
    'EUR',
    'https://amzn.to/3Cyprus3',
    'https://m.media-amazon.com/images/I/81VxMrmFbRL.jpg',
    'Food & Treats',
    'Dry Cat Food',
    'Hill''s Science Diet',
    4.6,
    12876,
    'in_stock',
    true,
    false,
    'Hill''s Science Diet Indoor Cat Food Cyprus - Vet Recommended',
    'Buy Hill''s Science Diet indoor cat food in Cyprus. Veterinarian-recommended nutrition for healthy indoor cats.',
    ARRAY['cat food', 'indoor cats', 'veterinarian recommended', 'cyprus pets', 'chicken recipe']
  ),
  (
    'Cat Mate Elite Super Selective Electronic Cat Flap',
    'The Cat Mate Elite Super Selective Electronic Cat Flap uses your cat''s unique microchip to allow selective entry and exit. Battery operated with long battery life. Perfect for multi-cat households in Cyprus to control which cats can enter.',
    'Microchip-activated cat flap for selective access',
    'B07GDWQBCH',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    129.99,
    149.99,
    'EUR',
    'https://amzn.to/3Cyprus4',
    'https://m.media-amazon.com/images/I/71bKhP0gFzL.jpg',
    'Doors & Gates',
    'Cat Flaps',
    'Cat Mate',
    4.4,
    2156,
    'in_stock',
    true,
    true,
    'Cat Mate Electronic Cat Flap Cyprus - Microchip Activated',
    'Buy Cat Mate electronic cat flap in Cyprus. Microchip-activated for selective pet access control.',
    ARRAY['cat flap', 'microchip activated', 'pet access', 'cyprus pets', 'security']
  ),
  -- Pet Care & Health
  (
    'FURminator deShedding Tool for Large Dogs',
    'The FURminator deShedding Tool reduces shedding by up to 90% when used regularly. Features a stainless steel deShedding edge that reaches through the topcoat to safely remove loose undercoat hair. Essential for Cyprus pet owners dealing with seasonal shedding.',
    'Professional pet grooming tool reduces shedding by 90%',
    'B0040QH8D4',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    34.99,
    39.99,
    'EUR',
    'https://amzn.to/3Cyprus5',
    'https://m.media-amazon.com/images/I/71dKj3F3lSL.jpg',
    'Grooming',
    'Deshedding Tools',
    'FURminator',
    4.7,
    25643,
    'in_stock',
    true,
    false,
    'FURminator deShedding Tool Cyprus - Reduce Pet Hair 90%',
    'Buy FURminator deShedding tool in Cyprus. Professional grooming reduces shedding by 90% for cleaner homes.',
    ARRAY['pet grooming', 'deshedding', 'pet hair', 'cyprus pets', 'professional tool']
  ),
  (
    'Benebone Real Flavor Wishbone Dog Chew Toy, Bacon Flavor',
    'The Benebone Wishbone is designed for power chewers and infused with 100% real bacon flavor. Made in the USA with super-strong nylon and curved for a paw-friendly grip. Perfect for medium dogs in Cyprus who love to chew.',
    'Bacon-flavored power chew toy for medium dogs',
    'B00T4BQIAU',
    (SELECT id FROM affiliate_networks WHERE name = 'Amazon Associates'),
    12.99,
    15.99,
    'EUR',
    'https://amzn.to/3Cyprus6',
    'https://m.media-amazon.com/images/I/71hQx8TI4RL.jpg',
    'Toys',
    'Chew Toys',
    'Benebone',
    4.5,
    18745,
    'in_stock',
    true,
    false,
    'Benebone Bacon Chew Toy Cyprus - Power Chewer Approved',
    'Buy Benebone bacon-flavored chew toy in Cyprus. Perfect for power chewing dogs who need durable toys.',
    ARRAY['dog toys', 'chew toys', 'bacon flavor', 'cyprus pets', 'power chewers']
  );